#!/usr/bin/env bash

if [[ $1 != "" ]]; then
  cat $1 | docker exec -i zabbix_db /usr/bin/mysql -u zabbix --password=zabbix zabbix
else
  docker exec zabbix_db /usr/bin/mysqldump -u zabbix --password=zabbix zabbix > zabbix-$(date +%F).sql
fi
