#!/usr/bin/env bash

source .env

if [[ $1 != "" ]]; then
  cat $1 | docker exec -i zabbix_db /usr/bin/mysql -u $DB_USER --password=$DB_PASSWORD $DB_DATABASE
else
  docker exec zabbix_db /usr/bin/mysqldump -u $DB_USER --password=$DB_PASSWORD $DB_DATABASE > zabbix-$(date +%F).sql
fi
