#!/usr/bin/env bash

source .env

if [[ $1 != "" ]]; then
  cat $1 | docker exec -i zabbix_db /usr/bin/mysql -u $MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE
else
  docker exec zabbix_db /usr/bin/mysqldump -u $MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE > zabbix-$(date +%F).sql
fi
