version: '3'

services:
  zabbix_db:
    image: postgres:13
    container_name: zabbix_db
    hostname: zabbix_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
    networks:
      - zabbix_net

  zabbix_app:
    container_name: zabbix_app
    hostname: zabbix_app
    build: ./server
    ports:
      - 10051:10051
    restart: always
    environment:
      DB_SERVER_HOST: zabbix_db
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    links:
      - zabbix_db
    networks:
      - zabbix_net

  zabbix_web:
    container_name: zabbix_web
    hostname: zabbix_web
    image: zabbix/zabbix-web-nginx-pgsql:latest
    links:
      - zabbix_db
      - zabbix_app
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_SERVER_HOST: zabbix_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      ZBX_SERVER_HOST: zabbix_app
      ZBX_SERVER_NAME: MyZabbix
      PHP_TZ: "Europe/Kiev"
    networks:
      - zabbix_net

networks:
  zabbix_net:
