version: '2'

volumes:
  db:
  certs:
  vhost.d:
  html:

networks:
  zabbix_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

services:
  db:
    image: mysql:latest
    container_name: zabbix_db
    hostname: zabbix_db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
    networks:
      zabbix_net:
        ipv4_address: 172.28.0.2

  app:
    container_name: zabbix_app
    hostname: zabbix_app
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - 10051:10051
    restart: always
    environment:
      - DB_SERVER_HOST=172.28.0.2
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
    links:
      - db
    volumes:
      - ./scripts/externalscripts:/usr/lib/zabbix/externalscripts
      - ./scripts/alertscripts:/usr/lib/zabbix/alertscripts
    networks:
      zabbix_net:
        ipv4_address: 172.28.0.3

  web:
    container_name: zabbix_web
    hostname: zabbix_web
    image: zabbix/zabbix-web-apache-mysql:latest
    links:
      - db
      - app
    restart: always
    environment:
      - DB_SERVER_HOST=172.28.0.2
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - ZBX_SERVER_HOST=172.28.0.3
      - ZBX_SERVER_NAME=MyZabbix
      - PHP_TZ="Europe/Kiev"
      - VIRTUAL_HOST=domain.example.xy
      - LETSENCRYPT_HOST=domain.example.xy
      - LETSENCRYPT_EMAIL=mail@example.xy
    networks:
      zabbix_net:
        ipv4_address: 172.28.0.4

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    links:
      - web
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      zabbix_net:
        ipv4_address: 172.28.0.5

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      zabbix_net:
        ipv4_address: 172.28.0.6

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      zabbix_net:
        ipv4_address: 172.28.0.7
    depends_on:
      - proxy
