version: '3'

volumes:
  db:
  certs:
  vhost.d:
  html:
  grafana:

services:
  db:
    image: mysql:latest
    container_name: zabbix_db
    hostname: zabbix_db
    restart: always
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  app:
    container_name: zabbix_app
    hostname: zabbix_app
    build: ./server
    ports:
      - 10051:10051
    restart: always
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    links:
      - db
    volumes:
      - ./scripts/externalscripts:/usr/lib/zabbix/externalscripts
      - ./scripts/alertscripts:/usr/lib/zabbix/alertscripts

  web:
    container_name: zabbix_web
    hostname: zabbix_web
    image: zabbix/zabbix-web-apache-mysql:latest
    links:
      - db
      - app
    restart: always
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: 172.28.0.3
      ZBX_SERVER_NAME: MyZabbix
      PHP_TZ: "Europe/Kiev"
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${MAIL}

  grafana:
    container_name: grafana
    hostname: grafana
    build: ./grafana
    ports:
      - 3000:3000
    links:
      - web
    restart: always
    volumes:
      - certs:/etc/letsencrypt/certs:ro
      - grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_CERT_FILE: /etc/letsencrypt/certs/${DOMAIN}.crt
      GF_SERVER_CERT_KEY: /etc/letsencrypt/certs/${DOMAIN}.key
      GF_SERVER_PROTOCOL: https

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
