#!/usr/bin/env bash

source .env

docker exec -it zabbix_db mysql -u root --password=$MYSQL_ROOT_PASSWORD -e "ALTER USER '$MYSQL_USER' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD';"
docker exec -u 0 zabbix_app apk add curl
docker exec -it grafana grafana-cli plugins install alexanderzobnin-zabbix-app
docker restart grafana
