#!/bin/sh

CHAT_ID="$1"
TOKEN="$2"
SUBJECT="$3"
MESSAGE="$4"

NL="
"

curl --silent -X POST --retry 5 --retry-delay 0 --retry-max-time 60 --data-urlencode "chat_id=${CHAT_ID}" --data-urlencode "text=${SUBJECT}:${NL}${NL}${MESSAGE}" "https://api.telegram.org/bot${TOKEN}/sendMessage?disable_web_page_preview=true" | grep -q '"ok":true'
